(TeX-add-style-hook "preamble"
 (lambda ()
    (TeX-run-style-hooks
     "babel"
     "english"
     "color"
     "usenames"
     "inputenc"
     "latin1"
     "pgflibraryarrows"
     "pgflibrarytikztrees"
     "pgflibraryshapes"
     "tikz"
     "pgf"
     "listings"
     "times"
     "ccmap"
     "CJK"
     "latex2e"
     "beamer10"
     "beamer"
     "13pt"
     "cjk"
     "macros")))

