(TeX-add-style-hook "preamble"
 (lambda ()
    (TeX-run-style-hooks
     "babel"
     "english"
     "inputenc"
     "latin1"
     "pgflibrarytikztrees"
     "pgflibraryshapes"
     "tikz"
     "pgf"
     "listings"
     "times"
     "ccmap"
     "CJK"
     "attachfile"
     "hyperref"
     "fullpage"
     "xcolor"
     "svgnames"
     "beamerarticle"
     "noxcolor"
     "latex2e"
     "art10"
     "article"
     "a4paper"
     "macros")))

